server:
  port: 8082

spring:
  application:
    name: ms-producto-service

  datasource:
    url: jdbc:mysql://localhost:3307/chinito_producto_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  categoria:
    url: http://localhost:8081/api/categorias

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

resilience4j.circuitbreaker:
  instances:
    productoByIdCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10